meta_product_name: "SurpriseMe!"
meta_title: "Santa's not the only one with secrets."
meta_description: "A gifting app that helps you to pick a gift tailored to your recipient's preferences."
meta_image: "logo.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards